#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Tue Aug 25 11:21:23 GMT 2026
android.nonTransitiveRClass=true
org.gradle.daemon.idletimeout=10800000
systemProp.user.country=US
systemProp.user.language=en
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=37.0
kotlin.code.style=official
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
android.aapt2FromMavenOverride=/data/user/0/com.tom.rv2ide/files/home/.androidide/aapt2
