plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    // AGP 9.0+ 内置 Kotlin 支持：org.jetbrains.kotlin.android 不再需要单独应用
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "com.bail.lspfrifa"
    // Miuix 0.9.3 与 libxposed 102.0.0 的 AAR metadata 要求 API 37。
    compileSdk = 37
    // 显式指定 NDK：避免 AGP 回退到其内置默认版本 (27.0.12077973)
    ndkVersion = "28.2.13676358"
    // compileSdk 与 build-tools 可独立设置；35.0.1 内置 arm64 aidl，37.0.0 版本是 x86_64，不能在本机执行。
    buildToolsVersion = "35.0.1"

    defaultConfig {
        applicationId = "com.bail.lspfrifa"
        // minSdk 26：保持现有 LSPosed 宿主兼容基线（底栏已改轻量自绘，无需 blur 库的 API33 要求）
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        ndk {
            // frida-gumjs devkit 提供 arm64 / arm 两套静态库；按需增减
            abiFilters += listOf("arm64-v8a", "armeabi-v7a")
        }

        externalNativeBuild {
            cmake {
                cppFlags += "-std=c++17"
                arguments += "-DANDROID_STL=c++_static"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            // t14：RV2IDE usr/bin/cmake 环境失效 → SDK 3.22.1 重新替换为 4.1.2 内容（见构建说明）
            version = "3.22.1"
        }
    }

    buildFeatures {
        viewBinding = true
        aidl = true
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        // t5：sora-editor language-textmate 契约要求 API<33 开启 core-library desugaring（宿主 minSdk 26<33）
        isCoreLibraryDesugaringEnabled = true
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)

    // Compose Multiplatform 1.11.1 Android artifacts，和 Miuix 0.9.3 对齐
    implementation(libs.compose.foundation)
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.icons.extended)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.viewmodel.compose)
    implementation(libs.kotlinx.coroutines.android)
    // Compose Navigation：项目模块路由（主页面 / 选择项目全屏页 / 项目详情）
    implementation(libs.androidx.navigation.compose)
    debugImplementation("org.jetbrains.compose.ui:ui-tooling:1.12.0-rc01")

    // Miuix 0.9.4-rc01 原生模块
    implementation(libs.miuix.ui)
    implementation(libs.miuix.preference)
    // miuix-blur（玻璃拟态）：AAR minSdk33 已用 <uses-sdk tools:overrideLibrary> 正确放行（官方方式）；
    // 运行时 isRuntimeShaderSupported gate 保证 API<33 降级纯色、零崩溃风险
    implementation(libs.miuix.blur)
    // libxposed 现代规范（阶段二使用；compileOnly：运行时由 LSPosed 框架提供）
    compileOnly("io.github.libxposed:api:102.0.0")
    // 模块宿主 App 通过该服务与 LSPosed 通信，用于真实激活状态、scope 等
    implementation("io.github.libxposed:service:102.0.0")

    // sora-editor 0.23.6：详情页脚本代码编辑器（替换 Miuix TextField；View 体系 CodeEditor，零 Compose 依赖）
    implementation(libs.sora.editor)
    // sora-editor TextMate 语法高亮（JS grammar + VSCode 主题资源；runtime 传递 joni/jcodings/gson/snakeyaml-engine 等）
    implementation(libs.sora.textmate)
    // t5：language-textmate API<33 需要 core-library desugaring（2.1.5 = google maven 最新稳定）
    coreLibraryDesugaring(libs.desugar.jdk.libs)
    // Monet 主题（材料3 动态色：dynamicLightColorScheme/dynamicDarkColorScheme 读取系统壁纸色）
    // ——用户明确：引入 M3 的目的 = 支持 Monet 主题（非组件仿制）
    implementation(libs.compose.material3)

}